# Generated by Django 5.1.1 on 2025-07-19 02:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_users_name_alter_users_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/services_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/services_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/services_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/services_images/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.users')),
            ],
        ),
    ]
